language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_SECRET
    - secure: Jt+Dkax47Metdl3qmp2Zj53WiemdEtDQGsAWm/zh9IdiCJunBSeHke7P5k3vmIJA0NBTbkyBCJRLouwC+T/9t0Ioajb41kOE4Eoymt29Wwl7aScALr16gbdvDQRFIPaNdedoTG5c1ZGroP5IbzbN+KVOf+KMjfKpVI4OQsgM25f5WsACo/uwmjNSkND4sRyfjxxV79NPoM9WOyk2WTnINOekO8vbMZxFPuuj7zGuTZyHcblr5xrI/w0LOlUP8tXlfIFiNyX1kG40RUojVHdt6CC9tNyiQt9ba6oVg3B1Fhp5+jikrdi/KSL+CdmJP3Sgc07TH1hvCiZ448kyfhcoRe/IeLiffiVmNVK13cI46bt8Hic9yOX6seaOgMeWTkDIq3ryDpKgJg8Z7flrUCYqKJdqYrfww6R4UFKK5SxTqLSlEtxe2H53v/fUALxjPCi2Uts3po0mG8VRCP9ODy6vEE3uh9trv/34U0r/hbd4q6KEG5NftVc20sxsqsbiW+jZ5jalya1VoTEG9MEWyT3TKQL7ZqG9rdUsDZuTEmidxzp9xavZkj78Fq0eARzjpZDJdsckpuiJB48RRBiwDGz15tf7fnrJnvxKhLyJLK8TD6VP+J9xC6Lqe/H/EtKjT5fDjjOJZ/RyNSeIbjM061VQj8rZjuiF8T/A8Vr1HtBmnK0=
    # FIREBASE_TOKEN
    - secure: ymwbjdhBpAlNdLwuWkO9Ww1c1k/5QOuzZwOqGQC2wsuxUIXVzSw+ZhUy3ewhTZunvQvffX+dhGlJ2H5+bY2VHbbE4gINZhgYum5Fvv0BDab0WC4WDa3bIzmBnvDu5Ktyq+xhAC/4M2S4t1sO9WWbLyZKm7svu5h3yY7ADaRvGeUD/TUN0kd+CH5Z/96k8vEbLZ8LVto3QrVRZbtntfnYzsLSEg0AegnB9we454I4DnV9t3StuUfyliw6mupFmUe28dVGdkaKYFD6M18OK76EftBHLdvx8UOqFU/7+6KAYSp4pNjiEn6LXNls7hxVAQjsyCObCqtY0NKQJohiBd1refnnHgUesAX+4FUR78wqrgSeddjbGCTds1ffjOjKpNY1YTeqD/X1ygjt8Kxg6Tn80W2lw/Q2XvZbF8wwNsRBcBaNocaSioWR+ycDXPhyQA7kqKz28H/sZC0BMT8E6HcNmOC9aOYtJ9wrxQqwe+RzAEG0E9xFxZ+o9J74SxLZw/PRHxlXpFFOjJPm87XqiAd9FJIE8teX4qAzeJZzxqIMsvdEEcUL3YR92auFw7mbbtm6/e+tYl1v9BQSlQzartl5cEGFF+iTOXCsS3MyEaMmBnunbj+q7vHfB0UJ0l511/UIBsaxC0dNzhJMxpeZ6bHKbAdOBeJXLubTb1XofDeaY98=
